#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

echo
echo "=================================="
echo "   NINTERNETES OS v0.1 (PowerPC)"
echo "   Powered by Ju4nlux"
echo "=================================="
echo

# Network (DHCP)
if command -v udhcpc >/dev/null; then
  udhcpc -i eth0
fi

echo
echo "[i] System ready. SSH is manual."
echo "[i] Start SSH with:  start-ssh"
echo

exec /bin/sh
