#!/bin/sh
export PATH=/bin:/sbin:/usr/bin:/usr/sbin
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
mount -t devtmpfs none /dev

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts



# === NINTERNETES_KEEPALIVE ===
echo "[!] PID1 keepalive: /init must never exit. Dropping to shell loop."
while true; do
  /bin/sh
  echo "[!] Shell exited, restarting in 1s..."
  sleep 1
done
